#!/bin/bash

BASE_DIR=${PWD}
echo "AppImage Packager Script:"
echo "-------------------------"
echo ""
read -p "AppDir Path: " APPDIR_PATH
read -p "AppImage Name: " APPIMAGE_NAME
read -p "AppImage Target Architecture: " APPIMAGE_ARCHITECTURE
read -p "Application Version: " APPLICATION_VERSION
echo ""

SOURCE_DIR=$BASE_DIR/$APPDIR_PATH
TARGET_FILE=$BASE_DIR/_BUILD/$APPIMAGE_NAME-$APPLICATION_VERSION-$APPIMAGE_ARCHITECTURE.AppImage

mkdir -p $BASE_DIR/_BUILD
rm $TARGET_FILE
$BASE_DIR/AppImageAssistant $SOURCE_DIR $TARGET_FILE
chmod 777 $TARGET_FILE

echo "AppImage packing completed."
echo "Output AppImage at: " $TARGET_FILE
echo ""
read -p "Press any key to exit."

